services:
  todo-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: todo-server
    restart: unless-stopped
    env_file:
      - .env

  todo-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: todo-client
    restart: unless-stopped
    depends_on:
      - todo-server
    ports:
      - "8080:80"
