  todo-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: todo-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    mem_limit: 256m
